apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: {{ template "laravel.fullname" . }}
    name: {{ template "laravel.fullname" . }}
    namespace: default
spec:
    replicas: 3
    revisionHistoryLimit: 1
    strategy:
        type: RollingUpdate
    selector:
        matchLabels:
            app: {{ template "laravel.fullname" . }}
    template:
        metadata:
            labels:
                app: {{ template "laravel.fullname" . }}
        spec:
            containers:
                -   
                    name: nginx
                    image: {{ .Values.image.nginx.repository }}
                    ports:
                        - 
                            containerPort: 80
                    volumeMounts:
                        - 
                            name: volume-nginx
                            mountPath: /etc/nginx/conf.d/default.conf
                            subPath: default-conf-file
                -
                    name: php
                    image: {{ .Values.image.phpLaravel.repository }}
                    volumeMounts:
                        - 
                            name: volume-laravel
                            mountPath: /var/www/html/.env
                            subPath: env-file
            volumes:
                - 
                    name: volume-nginx
                    configMap:
                        name: configmap-nginx
                - 
                    name: volume-laravel
                    configMap:
                        name: configmap-laravel
                
